### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by avenmia** [CodeWithAloha/HIERR#198]
For this task, add Jest and React Testing Library to the project and add at least one test. 
References:
https://jestjs.io/
https://testing-library.com/docs/react-testing-library/intro/

**Comment by avenmia** [comment]
https://testing-library.com/docs/react-testing-library/intro/

**Comment by kobebuckley** [comment]
I checked the Jest library and it is not fully compatible with Vite. It has some fixes that are currently in progress on the repo for vite-jest https://github.com/sodatea/vite-jest/tree/main/packages/vite-jest#limitations-and-differences-with-commonjs-tests
and https://jestjs.io/docs/ecmascript-modules#differences-between-esm-and-commonjs which has a warning for using it. 

I'll use the original Vitest https://vitest.dev/ that we mentioned before in the meeting to replace Jest due to the compatibility issue.
